server:
  port: 8085

otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  resource:
    attribute:
      service.name: invoice-service
      service: invoice-service
      env: dev